# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 07:27
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.FileField(blank=True, upload_to=books.models.cover_upload_path)),
            ],
        ),
    ]
